name: Build and Test

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Setup Node 10
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Install yarn and load dependencies
      run: |
        npm install yarn -g
        cd /home/runner/work/CS3010-FinalYearProject/CS3010-FinalYearProject/Revoked.Web/Client
        yarn
        yarn postinstall
    - name: Build
      run: dotnet build --configuration Debug
    - name: Test
      run: yarn test
